Feature/homework2
mariami-tchanturia/react-global-mentoring pull request #2
Opened 2023-03-27 14:59 UTC by mariami-tchanturia

2023-04-03 21:43 UTC, stepan-lagunovsky requested changes

2023-04-03 21:43 UTC, stepan-lagunovsky commented on cypress/support/commands.js
> +// ***********************************************
Remove these files since you do not use code.

2023-04-03 21:43 UTC, stepan-lagunovsky commented on src/components/Counter/Counter.test.js
> +    fireEvent.click(screen.getByText(/decrement/i));
Please check these string values. Here it should start from the upperase: `Decrement`

2023-04-03 22:56 UTC, mariami-tchanturia commented on src/components/Counter/Counter.test.js
> +import { render, screen, fireEvent } from '@testing-library/react';
Good to know, thank you!

2023-04-03 22:57 UTC, mariami-tchanturia commented on cypress/support/commands.js
> +// ***********************************************
Good point, removed the whole support folder as soon as I don't use the files inside it.

2023-04-03 22:58 UTC, mariami-tchanturia commented on src/components/Counter/Counter.test.js
> +    fireEvent.click(screen.getByText(/decrement/i));
Here I used the i flag for a case insensitive search, so that it finds an element in any case.

2023-04-04 10:33 UTC, stepan-lagunovsky commented on src/components/Counter/Counter.test.js
> +    fireEvent.click(screen.getByText(/decrement/i));
Here everything depends on what are you going to test.
We have just two elements with completely different text.
And if someone change it to lowercase - test will pass.
So if we want to prevent the user from changing the label - even it's text-transform - we can change this. But on the other hand - again - this will work as well.

2023-04-04 10:34 UTC, stepan-lagunovsky approved these changes

2023-04-04 11:57 UTC, merged