Feature/homework3
mariami-tchanturia/react-global-mentoring pull request #3
Opened 2023-04-03 12:01 UTC by mariami-tchanturia

2023-04-04 10:46 UTC, stepan-lagunovsky commented on src/App.js
> +
Here in this module I would suggest you to create one more commit and setup `husky`.
This is a package on NPM.

A tiny note here.
In the documentation - you will see such string.
`npx husky add .husky/pre-commit "npm test"`

Please create one more field in package.json `scripts` -> 'precommit' and as a value set lint tests and to run tests.
And then call this with a newly created script `npx husky add .husky/pre-commit "npm prepublish"`

Then make sure that when you commit something - husky will run all tasks from script - and fail if you have some failed tests or un-linted changes.

2023-04-04 10:53 UTC, stepan-lagunovsky commented on src/components/Header/Header.js
> +function Header({preview, setPreview}) {
Please check all coponents in project and express function declarations into arrow functions

2023-04-04 11:30 UTC, stepan-lagunovsky requested changes

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/components/SortControl/SortControl.js
> +	function handleChange(e) {
1) Please use arrow functions.
2) And it is better to avoid such 1-letter params. Use `event` instead. It is more readable.
BTW. In such  case here you can do even better. You can remove `const { value } = e.target;` and use props destructuriong for event right in function param.
Then use value directly from there to your onSort callback, and set state callback.

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/components/SortControl/SortControl.js
> +          {options.map(({id, name}) => (
Nice! If you do not have any conflicts with props - this variant is more readable.

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/constants/index.js
> +export {GENRES, MOVIES, SELECT_OPTIONS}
It is better to remove this and export constants one by one here.
```
export const ......
export const ......
.....
```

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/components/MoviesListing/MoviesListing.js
> +	return (
Since you have a clear view - you can simply export arrow function and return jsx right after an arrow `=> (...)`

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/components/MovieMenu/MovieMenu.js
> +			<button className={styles.movieMenu_dots} onClick={() => setIsOpened(prev => !prev)}>
1) It is better to change `prev` to `prevState`. Will be a bit more readable.
2) You can also change `<span></span>` into `<span />` Like you did for logo inside footer component.

2023-04-04 11:30 UTC, stepan-lagunovsky commented on src/common/Button/Button.module.scss
> +	padding: 6.33px 14px 7.67px 23px;
Avoid such numbers in code. Of course usually we have some designs - but this .12345678 - make it hard to keep consistency for values in projects.
Maybe it's better to add this paddings: `padding: 5px 15px 8px 24px;`

2023-04-04 20:06 UTC, stepan-lagunovsky commented on src/components/GenreSelect/GenreSelect.js
> +        {genres.map((option) => (
Nice place to apply object destructuring`{genres.map(({ id, name }) => (`

2023-04-04 20:08 UTC, stepan-lagunovsky commented on src/components/MovieDetail/MovieDetail.js
> +  return (
Please add empty line here

2023-04-04 20:09 UTC, stepan-lagunovsky commented on src/components/MovieMenu/MovieMenu.js
> +        onClick={() => setIsOpened((prev) => !prev)}
Use more specific words: `prev` -> `prevState`

2023-04-04 20:12 UTC, stepan-lagunovsky commented on src/components/SortControl/SortControl.js
> +  function handleChange(e) {
1) Use arrow functions for components and methods.
2) Here as well. `event` will be better here.
BTW - we can use object destructuring here as well:
```
  const handleChange = ({ target }) => {
    const { value } = target;

    setSelectedOption(value);
    onSort(value);
  }
```

2023-04-04 20:19 UTC, stepan-lagunovsky commented on src/constants/index.js
> +const GENRES = [
`GENRES` ->`GENRES_OPTIONS`

2023-04-04 20:22 UTC, stepan-lagunovsky commented on src/constants/index.js
> +export { GENRES, MOVIES, SELECT_OPTIONS };
Just export each constant directly. 
```
export const ......
export const ......
....
```

2023-04-04 20:22 UTC, mariami-tchanturia commented on src/common/Button/Button.module.scss
> +	padding: 6.33px 14px 7.67px 23px;
I totally agree, just simply copy-pasted values from Figma, since the course doesn't focus on CSS very much. Generally I would change a lots of things in stylesheets- use variables for colors and sizes, also would use relative units for fonts at least, add some mixins, etc.

2023-04-05 07:53 UTC, stepan-lagunovsky commented on src/components/MovieTile/MovieTile.jsx
> +  const handleDlete = () => {};
Just a tiny typo: `handleD-E-lete -> handleDelete`

2023-04-06 23:46 UTC, stepan-lagunovsky requested changes

2023-04-06 23:46 UTC, stepan-lagunovsky commented on .storybook/main.js
> +/** @type { import('@storybook/react-webpack5').StorybookConfig } */
1) Add `.storybook/preview-body.html`
2) Add there:
```
<style>
  body {
    margin: 0;
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
  }
</style>
```

2023-04-06 23:46 UTC, stepan-lagunovsky commented on src/components/MoviesListing/MoviesListing.jsx
> +import { GenreSelect, MovieTile, SortControl } from '..';
1) Change this line into 
```
import GenreSelect from '../GenreSelect/GenreSelect';
import SortControl from '../SortControl/SortControl';
import MovieTile from '../MovieTile/MovieTile';
```
2) `MovieTile.jsx` ->`import MovieMenu from '../MovieMenu/MovieMenu';`

2023-04-06 23:46 UTC, stepan-lagunovsky commented on src/components/MovieTile/MovieTile.jsx
> +import { MovieMenu } from '..';
Change into ` import MovieMenu from '../MovieMenu/MovieMenu';`

2023-04-07 16:44 UTC, stepan-lagunovsky approved these changes

2023-04-07 16:50 UTC, merged