Feature/homework4
mariami-tchanturia/react-global-mentoring pull request #4
Opened 2023-04-10 22:27 UTC by mariami-tchanturia

2023-04-11 08:24 UTC, stepan-lagunovsky requested changes

2023-04-11 08:30 UTC, stepan-lagunovsky reviewed
Believe that now - it's time for "husky" and "lint-staged".

I didn't leave a few comments on purpose so you can set up these two packages correctly and try to detect these errors on commit.
(A tiny note here. Please move settings for lint-staged into .lintstagedrc)

BTW. If we make some lint improvements - lets do the folowing:
1) Move your .eslintrc.json to the root and move "eslintConfig" piece from "package.json" there.
2) For browser list you can install 'browserslist' from npm and move browserlist settings to '.browserlistrc'. Just check the docks.

.browserlistrc ->

```
[production]> 1%
>0.2%
not dead
not op_mini all

[development]
last 1 chrome version
last 1 firefox version
last 1 safari version
```


and etc. For now just this.

An idea is to keep package.json only for package managing stuff.

2023-04-11 12:38 UTC, stepan-lagunovsky requested changes

2023-04-11 12:38 UTC, stepan-lagunovsky commented on src/App.js
> +import MovieListPage from './pages/MovieListPage/MovieListPage';
`import { Counter } from './components';`

2023-04-11 12:38 UTC, stepan-lagunovsky commented on src/common/Dialog/Dialog.jsx
> +import { createPortal } from 'react-dom';
```
import { createPortal } from 'react-dom';
import FocusTrap from 'focus-trap-react';
import PropTypes from 'prop-types';

import { Button } from '../../common';
import styles from './Dialog.module.scss';
import closeIcon from '../../assets/close-icon.png';
```

2023-04-11 12:38 UTC, stepan-lagunovsky commented on src/components/MovieForm/MovieForm.stories.js
> +import { MovieForm } from '../../components/MovieForm/MovieForm';
import { MovieForm } from '../../components';

2023-04-11 12:38 UTC, stepan-lagunovsky commented on src/components/MovieTile/MovieTile.jsx
> +import { DeleteConfirmation } from '../../components/DeleteConfirmation/DeleteConfirmation';
import { DeleteConfirmation, MovieMenu } from '../../components';

2023-04-11 12:38 UTC, stepan-lagunovsky commented on src/pages/MovieListPage/MovieListPage.jsx
> +import { Footer } from '../../components/Footer/Footer';
import { Header, Footer, MoviesListing } from '../../components';

2023-04-11 18:58 UTC, mariami-tchanturia commented on src/common/Textarea/Textarea.jsx
> +  labelText: PropTypes.string,
LabelText in Textarea component isn't required.

2023-04-11 20:32 UTC, stepan-lagunovsky requested changes

2023-04-11 20:32 UTC, stepan-lagunovsky commented on src/components/Header/Header.jsx
> +import { v4 as uuidv4 } from 'uuid';
'PropTypes' is defined but never used.

2023-04-11 20:32 UTC, stepan-lagunovsky commented on src/components/Header/Header.jsx
> +      <div className={`container-lg`}>
1) You can update this into className="container-lg".

2)There is no such `className` on the next line:
`styles.titleSearchWrapper`
Just `className='container-md'`

2023-04-11 20:32 UTC, stepan-lagunovsky commented on src/components/MovieForm/MovieForm.stories.js
> +import { MovieForm } from '../../components';
Just like this:
`import { MovieForm } from './MovieForm';`

2023-04-11 20:32 UTC, stepan-lagunovsky commented on src/components/MovieMenu/MovieMenu.jsx
>  import { Button } from '../../common/Button/Button';
import { Button } from '../../common';

2023-04-11 20:49 UTC, mariami-tchanturia commented on src/components/Header/Header.jsx
> +      <div className={`container-lg`}>
Fixed

2023-04-11 20:50 UTC, mariami-tchanturia commented on src/components/MovieMenu/MovieMenu.jsx
>  import { Button } from '../../common/Button/Button';
Fixed

2023-04-11 20:50 UTC, mariami-tchanturia commented on src/components/MovieForm/MovieForm.stories.js
> +import { MovieForm } from '../../components';
Fixed

2023-04-11 20:50 UTC, mariami-tchanturia commented on src/common/Textarea/Textarea.jsx
> +    <div className={styles.textareaWrapper}>
Fixed

2023-04-11 21:32 UTC, mariami-tchanturia commented on src/components/Header/Header.jsx
> +import { v4 as uuidv4 } from 'uuid';
Fixed

2023-04-12 07:11 UTC, stepan-lagunovsky approved these changes

2023-04-12 07:36 UTC, stepan-lagunovsky requested changes

2023-04-12 07:36 UTC, stepan-lagunovsky commented on src/components/MovieForm/MovieForm.jsx
> +        <Button className='btn--primary' onClick={() => handleSubmit(formData)}>
Please remove onClick

2023-04-12 07:42 UTC, stepan-lagunovsky requested changes

2023-04-12 10:15 UTC, stepan-lagunovsky approved these changes

2023-04-12 10:18 UTC, merged