Feature/homework5
mariami-tchanturia/react-global-mentoring pull request #5
Opened 2023-04-22 15:47 UTC by mariami-tchanturia

2023-04-22 20:49 UTC, stepan-lagunovsky requested changes

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={!src ? defaultPoster : src}
I think we can change this into:
`src={src ? src : defaultPoster}`  (First - true, then - false)
Or even better to this:
`src={src || defaultPoster} `

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/App.js
> +  console.log(movies);
Please remove this like in 'cleanup' commit

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/GenreSelect/GenreSelect.stories.js
> +  const [activeGenre, setActiveGenre] = useState();
You can remove this eslint-disable rule, then set initial state as `useState('Horror')` and pass `activeGenre` to `GenreSelect` prop

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={src === null ? defaultPoster : src}
Just like this: `src={src || defaultPoster}`

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MovieDetail/MovieDetail.jsx
> +        <MoviePoster src={poster_path} alt={`${title} poster`} />
In every place you use `MoviePoster` component it will be better to pass alt as a prop:
`<MoviePoster src={poster_path} alt={title} />`

But inside`MoviePoster` component set this combined `alt` value once:
`<img alt={`${alt} poster`} ... />`

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/GenreSelect/GenreSelect.jsx
> +            className={`${activeGenre === label ? styles.active : ''}`}
Since every prop is a string you can change it into:
`className={activeGenre === label ? styles.active : ''}`

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/SearchForm/SearchForm.jsx
> +  const handleSubmit = (event) => {
Since you use props inside this handler you can wrap it with `useCallback` and pass required dependencies to dependency array.

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MovieDetail/MovieDetail.jsx
> +    poster_path: PropTypes.string,
We already have `MovieType`.
So you can update `PropTypes` from this:
```
MovieDetail.propTypes = {
    activeMovie: PropTypes.shape({
        id: PropTypes.number.isRequired,
        title: PropTypes.string.isRequired,
        genres: PropTypes.arrayOf(PropTypes.string),
        release_date: PropTypes.string.isRequired,
        vote_average: PropTypes.number.isRequired,
        runtime: PropTypes.number.isRequired,
        overview: PropTypes.string.isRequired,
        poster_path: PropTypes.string,
  })
};
```
into:
```
MovieDetail.propTypes = {
    activeMovie: MovieType
};
```

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={src ? src : defaultPoster}
Yes. This is ok. But you can do this like this:
`src={src || defaultPoster}`

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MoviePoster/MoviePoster.jsx
> +  src: PropTypes.string,
I think you can set both props as required since everywhere you pass this props.

2023-04-22 20:49 UTC, stepan-lagunovsky commented on src/components/MovieTile/MovieTile.jsx
> +    poster_path: PropTypes.string.isRequired,
Please check this. This is a default prop.

2023-04-23 02:35 UTC, mariami-tchanturia commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={src === null ? defaultPoster : src}
Fixed

2023-04-23 02:36 UTC, mariami-tchanturia commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={!src ? defaultPoster : src}
Good idea, thanks!

2023-04-23 02:41 UTC, mariami-tchanturia commented on src/components/MovieDetail/MovieDetail.jsx
> +        <MoviePoster src={poster_path} alt={`${title} poster`} />
Fixed

2023-04-23 02:42 UTC, mariami-tchanturia commented on src/components/GenreSelect/GenreSelect.jsx
> +            className={`${activeGenre === label ? styles.active : ''}`}
Fixed

2023-04-23 02:46 UTC, mariami-tchanturia commented on src/components/GenreSelect/GenreSelect.stories.js
> +  const [activeGenre, setActiveGenre] = useState();
Fixed

2023-04-23 02:46 UTC, mariami-tchanturia commented on src/components/MoviePoster/MoviePoster.jsx
> +      src={src ? src : defaultPoster}
Done

2023-04-23 02:54 UTC, mariami-tchanturia commented on src/components/MovieDetail/MovieDetail.jsx
> +    poster_path: PropTypes.string,
You are right, thanks!

2023-04-23 03:06 UTC, mariami-tchanturia commented on src/components/MovieTile/MovieTile.jsx
> +    poster_path: PropTypes.string.isRequired,
You are right about alt attribute, although some of the movie source values are null and if I change it to required, it will throw an error, because null is considered nullable.

2023-04-23 03:06 UTC, mariami-tchanturia commented on src/components/MoviePoster/MoviePoster.jsx
> +  src: PropTypes.string,
You are right about alt attribute, although some of the movie source values are null and if I change it to required, it will throw an error, because null is considered nullable.

2023-04-23 03:09 UTC, mariami-tchanturia commented on src/components/MovieTile/MovieTile.jsx
> +    poster_path: PropTypes.string.isRequired,
Done

2023-04-23 07:42 UTC, stepan-lagunovsky requested changes

2023-04-23 07:42 UTC, stepan-lagunovsky commented on src/components/SearchForm/SearchForm.jsx
> +    [searchKeyword]
You have to add `setSearchQuery` as a dependency as well.

2023-04-23 07:44 UTC, stepan-lagunovsky commented on src/components/SearchForm/SearchForm.jsx
> +  const handleSubmit = (event) => {
https://github.com/mariami-tchanturia/react-global-mentoring/pull/5#discussion_r1174528524

2023-04-23 08:35 UTC, stepan-lagunovsky requested changes

2023-04-23 08:35 UTC, stepan-lagunovsky commented on src/components/MoviesListing/MoviesListing.jsx
> +import { GenreOptionsType } from '../../components/GenreSelect/GenreSelect';
`import { GenreOptionsType } from '../GenreSelect/GenreSelect';`

2023-04-23 10:28 UTC, mariami-tchanturia commented on src/components/MoviesListing/MoviesListing.jsx
> +import { GenreOptionsType } from '../../components/GenreSelect/GenreSelect';
Fixed this

2023-04-23 10:29 UTC, mariami-tchanturia commented on src/components/SearchForm/SearchForm.jsx
> +  const handleSubmit = (event) => {
Fixed

2023-04-23 11:05 UTC, stepan-lagunovsky approved these changes

2023-04-23 11:21 UTC, merged