Feature/homework6
mariami-tchanturia/react-global-mentoring pull request #6
Opened 2023-04-25 02:15 UTC by mariami-tchanturia

2023-04-25 08:28 UTC, stepan-lagunovsky requested changes

2023-04-25 08:28 UTC, stepan-lagunovsky commented on src/components/MovieDetail/MovieDetail.jsx
> +  } = activeMovie || {};
Do we need this?

2023-04-25 08:28 UTC, stepan-lagunovsky commented on src/pages/MovieDetailPage/MovieDetailPage.jsx
> +        <>
This fragment is redundant. Section - is already a wrapper.

2023-04-25 08:28 UTC, stepan-lagunovsky commented on src/pages/MovieDetailPage/MovieDetailPage.jsx
> +      {loading ? (
In such cases, on page level, it is better to organize code a bit different way.

```
if (loading) {
   return <Loading />
}

if (error) {
   return <Error />
}

if (something......) {
   return <Something />
}

if (something...) {
    <Navigate /> and etc.....
}

return <Section>...</Section>
```

Here like this:
```
if (loading) {
   return <Loading />
}

return <Section>...</Section>
```

2023-04-25 08:28 UTC, stepan-lagunovsky commented on src/pages/MovieListPage/MovieListPage.jsx
> +  const [error, setError] = useState(false);
You can try to do something like this... to avoid keeping this states unused. 
```
  if (loading) {
    return <Loading />;
  }
  
  if (error) {
    return <Navigate to="/somewhere" />;  // -> import { Navigate } from "react-router-dom";
  }

  return (
    <>
      <Outlet />
      <MoviesListing>
      ......
  );
```

2023-04-25 22:17 UTC, mariami-tchanturia commented on src/components/Header/Header.stories.js
> +  decorators: [
Fixed this

2023-04-25 22:18 UTC, mariami-tchanturia commented on src/components/MovieDetail/MovieDetail.jsx
> +  } = activeMovie || {};
Nothing, I removed it

2023-04-25 22:18 UTC, mariami-tchanturia commented on src/pages/MovieDetailPage/MovieDetailPage.jsx
> +        <>
Fixed this

2023-04-25 22:19 UTC, mariami-tchanturia commented on src/pages/MovieListPage/MovieListPage.jsx
> +  const [error, setError] = useState(false);
Fixed

2023-04-25 22:19 UTC, mariami-tchanturia commented on src/pages/MovieDetailPage/MovieDetailPage.jsx
> +      {loading ? (
Fixed

2023-04-26 07:02 UTC, stepan-lagunovsky requested changes

2023-04-26 07:02 UTC, stepan-lagunovsky commented on src/common/NotFound/NotFound.jsx
> +      <p className={styles.error_Text}>Page Not Found</p>
Here should be `_text} ...`

2023-04-26 07:02 UTC, stepan-lagunovsky commented on src/components/Header/Header.stories.js
> +  return <Header {...args} setSearchQuery={setSearchQuery} />;
Change back after fixing `AppRoutes`

2023-04-27 04:19 UTC, stepan-lagunovsky approved these changes

2023-04-27 04:25 UTC, stepan-lagunovsky requested changes

2023-04-27 04:25 UTC, stepan-lagunovsky commented on src/App.scss
> +.root {
`#root`

2023-04-27 04:54 UTC, stepan-lagunovsky requested changes

2023-04-27 04:54 UTC, stepan-lagunovsky commented on src/pages/NotFoundPage/NotFoundPage.module.scss
> +	height: 100vh;
In current implementation this 100vh breaks the layout.
Please remove this `100vh` to keep it in top section.
Maybe add  `padding: 50px 0;` or something instead.

2023-04-27 04:54 UTC, stepan-lagunovsky commented on .storybook/preview-body.html
> +	<div id="root" class="root"></div>
You do not need this className anymore.

2023-04-27 05:03 UTC, stepan-lagunovsky requested changes

2023-04-27 05:03 UTC, stepan-lagunovsky commented on src/components/MovieDetail/MovieDetail.jsx
> +            {parseInt(release_date) || ''}
Please change back:
```
    ...
    vote_average,
    runtime,
    poster_path,
  } = activeMovie || {};
```
Because this change works if you have bac-kend started.
But without back-end started when`activeMovie === null` - you will have an error on that page.
Because you can't destructure `null`.

2023-04-27 05:24 UTC, stepan-lagunovsky requested changes

2023-04-27 05:24 UTC, stepan-lagunovsky commented on src/pages/Layout/Layout.jsx
> +  }
Please move all the logic from this `Layout` component to `MoviesListing` component.
But inside MoviesListing page navigate to not-found page a bit different.
Using hook instead of returning a component.

```
  const navigate = useNavigate();

  useEffect(() => {
    navigate(PATH_NAMES.NotFound);
  }, [navigate]);
```

2023-04-27 11:49 UTC, stepan-lagunovsky approved these changes

2023-04-27 11:57 UTC, merged